name: "lambda-calculus"
version: '0.0.0'
github: "gb/lambda-calculus"
license: MIT
author: "Gabe Tobias"
maintainer: "Gabe Tobias"
synopsis: "Tiny Lambda-Calculus Interpreter"
description: "An extremely simple implementation of Lambda-Calculus in Haskell"
category: "Compilers/Interpreters"

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base
    - mtl
    - containers
    - parsec

tests:
  lambda-calculus-tests:
    source-dirs: test
    main: Test.hs
    dependencies:
    - base
    - tasty
    - tasty-hspec
    - lambda-calculus
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
